### PR TITLE
Merge pull request #1 from sivakumarkomma/master

### PR DESCRIPTION
**Pull request by tirunagarishyamkumar**
Give me code again for developement

### CODE REVIEW

**Comment by tirunagarishyamkumar** [comment]
Give Me Code

**Comment by sivakumarkomma** [comment]
Please change spring-jpa.xml into older version and again raise new pull request

**Comment by tirunagarishyamkumar** [comment]
new file from siva

**Comment by tirunagarishyamkumar** [comment]
i hv commited files pls review

**Pull request closed without merging**
